import React from 'react';
import './selected-work.css';
const github = 'https://github.com/Franksharpe008';
const linkedin = 'https://www.linkedin.com/in/therelentlessconnoisseur/';
const presentation = 'https://franksharpe-main-architect.vercel.app/presentation';
const projects = [
  ['Gemma · Sienna', 'Browser AI', 'gemma-standalone-immersion', 'https://gemma-standalone.vercel.app', 'Local language-model inference, streaming replies, and device speech. Loading is deliberate, with clear download and hardware requirements.', 'WebLLM · WebGPU · Browser speech', 'Requires a compatible GPU and model download'],
  ['Neon Rift', 'Game systems', 'neon-rift', 'https://neon-rift-one.vercel.app', 'A playable arena game with boss encounters, shootable upgrades, adaptive enemy behavior, effects, and desktop or touch controls.', 'Canvas · JavaScript · Web Audio', 'Adaptive game rules; no language model'],
  ['Chordloom', 'Creative tools', 'chordloom', 'https://chordloom-kappa.vercel.app', 'Turn style, key, tempo, and length into a piano progression. Play it and export MIDI or WAV for a music workflow.', 'Tone.js · MIDI · Offline rendering', 'Generative music rules; no hosted AI model'],
  ['Reelhouse Library', 'Product interfaces', 'reelhouse-library', 'https://reelhouse-library.vercel.app', 'Search a film catalog, filter by format and genre, inspect a title, and maintain a device-local watchlist across repeated controls.', 'Next.js · TypeScript · Local persistence', 'Film playback depends on external sources'],
  ['Magnetar Motion House', 'Cinematic interaction', 'magnetar-motion-house', 'https://magnetar-motion-house.vercel.app', 'A multi-page studio concept exploring Three.js motion, video controls, optional audio, responsive navigation, and reduced-motion behavior.', 'Three.js · Vite · JavaScript', 'Studio concept; project imagery is illustrative'],
];
export default function SelectedWork() {
  return <div className="selected-work">
    <a className="skip" href="#work">Skip to selected work</a>
    <header className="work-nav"><a className="wordmark" href="#top">FRANK D. SHARPE<span>OPERATIONS → SYSTEMS</span></a><nav aria-label="Professional profiles"><a href={github}>GitHub ↗</a><a href={linkedin}>LinkedIn ↗</a></nav></header>
    <main id="top"><section className="work-hero"><p className="eyebrow">Austin, Texas · Selected work</p><h1>From the factory floor<br/>to working software<span>.</span></h1><p className="hero-copy">I connect operational experience with AI-assisted development to build, test, and explain useful systems. The work spans workforce software, AI interfaces, games, and creative tools.</p><a className="primary-link" href={presentation}>Watch the working system ↗</a><a className="text-link" href="#work">Explore the source ↓</a></section>
      <section className="operating-proof" aria-labelledby="main-architect"><div><p className="eyebrow">01 / Operating problem → saved result</p><h2 id="main-architect">Main Architect</h2><p>Staffing requirements, schedules, attendance, and coverage decisions belong in one connected workflow. Main Architect brings them together; Aiden supports approved changes and reports.</p><p>I defined requirements and action boundaries, directed implementation, tested workflows, and corrected issues through reviewer feedback.</p><a href={presentation}>Watch the walkthrough ↗</a></div><div className="workflow" aria-label="Workflow"><span>Staffing requirements</span><b>↓</b><span>Schedule + attendance</span><b>↓</b><span>Coverage + reports</span><small>Fictional review workspace. Financial examples are illustrative. Use your supplied invitation to enter the application; product source is private.</small></div></section>
      <section id="work" className="project-section"><div className="section-intro"><p className="eyebrow">02 / Different problems. Working approaches.</p><h2>A broader view of the work.</h2><p>Explore each interface and its source. The notes explain what the project demonstrates and what it depends on.</p></div><div className="project-grid">{projects.map(([name,category,repo,site,text,stack,status],index) => <article className="work-card" key={repo}><div className="card-top"><span>{category}</span><span>0{index+2}</span></div><h3>{name}</h3><p>{text}</p><p className="stack">{stack}</p><small>{status}</small><div className="card-links"><a href={site}>Open project ↗</a><a href={`${github}/${repo}`}>View source ↗</a></div></article>)}</div></section>
      <section className="work-method"><p className="eyebrow">03 / How I deliver</p><h2>Understand it. Build it.<br/>Verify it. Teach it.</h2><p>My contribution combines manufacturing leadership, technical troubleshooting, client technology delivery, and hands-on work with AI development tools. Requirements, judgment, correction, and a result someone can inspect are central to the process.</p></section>
    </main><footer><span>Frank D. Sharpe · Practical AI & systems delivery</span><div><a href={github}>GitHub</a><a href={linkedin}>LinkedIn</a><a href={presentation}>Main Architect</a></div></footer>
  </div>;
}
